
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Mar 18 2025 15:19:54 -03 (Mar 18 2025 18:19:54 UTC)

// Verification Directory fv/sequential 

module sequential(A, B, C, rst, clk, Q, TM, scan_en, scan_in, scan_out);
  input A, B, C, rst, clk, TM, scan_en, scan_in;
  output [1:0] Q;
  output scan_out;
  wire A, B, C, rst, clk, TM, scan_en, scan_in;
  wire [1:0] Q;
  wire scan_out;
  wire [1:0] State_r;
  wire n_0, n_2, n_4, n_5, n_7, n_9, n_10, n_11;
  SEDFFX1 \State_r_reg[1] (.CK (clk), .D (n_11), .E (1'b1), .SI (n_0),
       .SE (scan_en), .Q (State_r[1]), .QN (scan_out));
  SEDFFX1 \State_r_reg[0] (.CK (clk), .D (n_10), .E (1'b1), .SI
       (scan_in), .SE (scan_en), .Q (State_r[0]), .QN (n_0));
  NOR2X1 g300__2398(.A (rst), .B (n_9), .Y (n_11));
  AOI21X1 g301__5107(.A0 (n_5), .A1 (n_7), .B0 (rst), .Y (n_10));
  AOI22X1 g302__6260(.A0 (C), .A1 (Q[0]), .B0 (State_r[0]), .B1 (n_4),
       .Y (n_9));
  OR3X1 g303__4319(.A (n_2), .B (State_r[1]), .C (State_r[0]), .Y
       (n_7));
  MXI2X1 g304__8428(.A (State_r[0]), .B (State_r[1]), .S0 (C), .Y
       (n_5));
  CLKXOR2X8 g305__5526(.A (State_r[1]), .B (State_r[0]), .Y (Q[0]));
  NOR2BX1 g306__6783(.AN (State_r[1]), .B (B), .Y (n_4));
  INVX1 g307(.A (A), .Y (n_2));
  BUFX6 drc_bufs314(.A (State_r[0]), .Y (Q[1]));
endmodule

