
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Feb 24 2025 09:29:07 -03 (Feb 24 2025 12:29:07 UTC)

// Verification Directory fv/sequential 

module sequential(A, B, C, rst, clk, Q);
  input A, B, C, rst, clk;
  output [1:0] Q;
  wire A, B, C, rst, clk;
  wire [1:0] Q;
  wire [1:0] State_r;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_7;
  DFFHQX1 \State_r_reg[1] (.CK (clk), .D (n_7), .Q (State_r[1]));
  NOR2X1 g300__2398(.A (rst), .B (n_6), .Y (n_7));
  DFFHQX8 \State_r_reg[0] (.CK (clk), .D (n_4), .Q (Q[1]));
  AOI22X1 g302__5107(.A0 (C), .A1 (Q[0]), .B0 (Q[1]), .B1 (n_1), .Y
       (n_6));
  AOI21X1 g301__6260(.A0 (n_2), .A1 (n_3), .B0 (rst), .Y (n_4));
  CLKXOR2X8 g305__4319(.A (State_r[1]), .B (Q[1]), .Y (Q[0]));
  OR3X1 g303__8428(.A (n_0), .B (State_r[1]), .C (Q[1]), .Y (n_3));
  MXI2X1 g304__5526(.A (Q[1]), .B (State_r[1]), .S0 (C), .Y (n_2));
  NOR2BX1 g306__6783(.AN (State_r[1]), .B (B), .Y (n_1));
  INVX1 g307(.A (A), .Y (n_0));
endmodule

